---
# Development Server
  - name: dev server provisioning
    hosts: dev
    become: yes
  
    tasks:
    - name: Install Maven
      apt:
        name: "{{ packages }}"
        #update_cache: yes
      vars:
        packages:
        - default-jdk
        - maven
        - git

    - name: Ensure maven package is present
      apt:
        name: maven
        state: present

    - name: Stop service nginx, if started
      service:
        name: nginx
        state: stopped
    - name: remove nginx package is present
      apt:
        name: nginx
        state: absent
    
    - name: clone boxfuse git repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
        dest: /root/boxfuse
    
    - name: Change the working directory to /root/boxfuse/ before executing the command.
      shell: mvn package -f /root/boxfuse/pom.xml
      args:
        chdir: /root/boxfuse/
  
    - name: Send WAR file to PROD node
      shell: rsync -avz hello-1.0.war root@54.93.235.89:/var/lib/tomcat9/webapps/hello-1.0.war
      args:
        chdir: /root/boxfuse/

# Production Server       
  - name: prod server provisioning
    hosts: prod
    become: yes
  
    tasks:
    - name: Update repositories cache and install "TomCat" package
      apt:
        name: tomcat9
        update_cache: yes
    
    - name: Stop service postgresql, if started
      service:
        name: postgresql
        state: stopped

    - name: remove postgresql package is present
      apt:
        name: postgresql
        state: absent
    
    - name: Ensure tomcat9 service is started
      service:
        name: tomcat9
        state: started