---
# Development Server
  - name: dev server provisioning
    hosts: dev
    become: yes
  
    tasks:
    - name: Install Maven
      apt:
        name: "{{ packages }}"
        #update_cache: yes
      vars:
        packages:
        - default-jdk
        - maven
        - git

    - name: Ensure maven package is present
      apt:
        name: maven
        state: present

    - name: Stop service nginx, if started
      service:
        name: nginx
        state: stopped
    - name: remove nginx package is present
      apt:
        name: nginx
        state: absent
    
    - name: clone boxfuse git repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
        dest: /root/boxfuse
    
    - name: Change the working directory to /root/boxfuse/ before executing the command.
      shell: mvn package -f /root/boxfuse/pom.xml
      args:
        chdir: /root/boxfuse/
  
    - name: Fetch WAR file to HOST
      fetch:
        src: /root/boxfuse/target/hello-1.0.war
        dest: /srv/hello-1.0.war
        flat: yes

# Production Server       
  - name: prod server provisioning
    hosts: prod
    become: yes
  
    tasks:
    - name: install jdk package
      apt:
        name: default-jdk
        #update_cache: yes
        
    - name: install "TomCat" package
      apt:
        name: tomcat9
    
    - name: Stop service postgresql, if started
      service:
        name: postgresql
        state: stopped

    - name: remove postgresql package is present
      apt:
        name: postgresql
        state: absent
    
    - name: Ensure tomcat9 service is started
      service:
        name: tomcat9
        state: started
    
    - name: Send WAR-file to prod
      copy:
        src: /srv/hello-1.0.war
        dest: /var/lib/tomcat9/webapps