- name: web server provisioning
  hosts: web
  become: yes
    
  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present
    - name: Ensure nginx service is started
      service:
        name: nginx
        state: started
    - name: replace
      lineinfile:
        path: /etc/selinux/config
        regexp: '^Welcome'
        line: WOW=enforcing