#С помощью контейнерного оркестратора docker-compose поднять2
# сервиса: сборочный и продовый. В сборочном сервисе должна
#происходить сборка Java приложения. В продовом сервисе -
#запуск приложения. Продовый образ должен быть минимальным
#по размеру.
version: '3.8'
services:
  app:                        # Build Application  
    build:                    
      context: ./tomcat9
    volumes:
      - data_volume:/root/boxfuse-sample-java-war-hello/target
    container_name: APP

  prod:                       # Run Application
    image: tomcat:9.0.40-jdk8-adoptopenjdk-openj9
    volumes:
      - data_volume:/usr/local/tomcat/webapps
    ports:
      - "8080:80"
    container_name: PROD

  volumes:
    - data_volume:  