#С помощью контейнерного оркестратора docker-compose поднять2
# сервиса: сборочный и продовый. В сборочном сервисе должна
#происходить сборка Java приложения. В продовом сервисе -
#запуск приложения. Продовый образ должен быть минимальным
#по размеру.
version: '3.8'
services:
  app:                        # Build Application  
    build:                    
      context: ./tomcat9
    volumes:
      - data_volume:/srv
    container_name: APP

  prod:                       # Run Application
    image: tomcat:jre8-alpine
    volumes:
      - data_volume:/usr/local/tomcat/webapps
    ports:
      - "80:8080"
    container_name: PROD
  
volumes:
  data_volume: