#С помощью контейнерного оркестратора docker-compose поднять2
# сервиса: сборочный и продовый. В сборочном сервисе должна
#происходить сборка Java приложения. В продовом сервисе -
#запуск приложения. Продовый образ должен быть минимальным
#по размеру.
version: '3.8'
services:
  build_app:                    
    build:                    # Build Application
      context: ./tomcat9