---
# tasks file for develop
  - name: Install Maven
    apt:
      name: "{{ packages }}"
      #update_cache: yes
    vars:
      packages:
      - default-jdk
      - maven
      - git

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Clone boxfuse git repository
    git: repo={{ repo_url }} dest={{ source }}

  - name: Build application
    shell: mvn package -f {{ source }}/pom.xml
    args:
      chdir:{{ source }}

  - name: Fetch WAR file to HOST
    fetch: src={{ target }}/hello-1.0.war dest=/srv/hello-1.0.war flat=yes